### PR TITLE
Sms test

### PR DESCRIPTION
**Pull request by jonathanshuai**
Appointments connects with database now and uses Twilio and api.ai.

### CODE REVIEW

**Comment by nmcdonaldd** [comment]
**Note:**
Twilio will only work with one hardcoded phone number for now. We need to find a way to verify the phone number requesting an appointment. Something to think about.

**Comment by zhl108** [comment]
Do not merge yet, still need:
1. work with front end to decide format of appointment data entity, and reconstruct the chat bot prompt accordingly;
2. automatically verified phone number on twilio

**Comment by zhl108** [comment]
having trouble of making this api work: https://www.twilio.com/docs/api/rest/outgoing-caller-ids, it seems that the Add A New Outgoing Caller ID API is broken.

**Comment by zhl108** [comment]
I contact their tech support, and they said once upgraded to premium account we don't need verification.... maybe thats the reason why they block this API of directly adding caller id on server side

**Comment by zhl108** [comment]
figure out a way to let any phone use the chat bot: 
1. user make a appointment on our website by entering their phone
2. if the phone entered has not been verified before, twilio will send out a validation call, by entering the code pop on the appointment page and hang up, the user will finish the verification process.
3. click close of the verification code alert box and the user will receive a greeting message.

**Pull request merged**
